version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: shop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: kehu2
      MYSQL_USER: kehu2
      MYSQL_PASSWORD: kehu2
      HTTP_PROXY: http://127.0.0.1:7890
      HTTPS_PROXY: http://127.0.0.1:7890
      NO_PROXY: localhost,127.0.0.1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/mini_shop.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - shop-network

  # 后端服务
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shop-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=kehu2
      - DB_PASSWORD=kehu2
      - DB_DATABASE=kehu2
      - PORT=4000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - shop-network
    command: npm run dev
    stdin_open: true
    tty: true

  # 前端服务
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: shop-frontend
    ports:
      - "4001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000/v1
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - shop-network
    command: npm run dev
    stdin_open: true
    tty: true

volumes:
  mysql_data:

networks:
  shop-network:
    driver: bridge
